server:
  port: 8080
  servlet:
    context-path: /
spring:
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_final?characterEncoding=UTF-8
    username: root
    password: "xxxx"
  ai:
    vectorstore:
      pinecone:
        api-key: xxxx
        index-name: book
        dimensions: 768
        similarity: cosine
    deepseek:
      api-key: xxxx
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0
    openai:
      api-key: xxxx
      base-url: https://api.siliconflow.cn/
      embedding:
        options:
          model: netease-youdao/bce-embedding-base_v1
          dimensions: 768
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gxa.pojo
  configuration:
    # 输出日志, 可以将真正的执行sql打印在控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰的自动识别命名规则: peopl_name-> peopleName
    map-underscore-to-camel-case: true
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
